name: Deploy Function App

on:
  push:
    branches: [ master ]
    paths:
      - 'AbevPortfolioCsharp.Backend/**'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: AbevPortfolioAzureFunction
      PROJECT_DIR: AbevPortfolioCsharp.Backend
      OUTPUT_DIR: publish_output
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Publish .NET
        working-directory: ${{ env.PROJECT_DIR }}
        run: dotnet publish -c Release -o ${{ env.OUTPUT_DIR }}
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v4
        with:
          app-name: ${{ env.APP_NAME }}
          package: ${{ env.PROJECT_DIR }}/${{ env.OUTPUT_DIR }}
